# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-11-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooveapp', '0002_auto_20171105_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeCardGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('whatHappended', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TreeWordsOneStory',
        ),
    ]
