# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-11-18 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooveapp', '0003_auto_20171118_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('names', models.CharField(max_length=100)),
                ('lobbyid', models.CharField(max_length=100)),
            ],
        ),
    ]
